[package]
name = "rpc_servcie"
version = "0.1.0"
edition = "2024"

[dependencies]
tarpc = { version = "0.32", features = ["serde-transport", "tokio1"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0"
clap = "4.5.41"
