title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- scripts
- target
- logs
- templates
ext:
- rs
lang: rust
enablerun: true
action:
  before:
  - echo "zzz start"
  after:
  - echo "zzz end"
  exit:
  - echo "exit"
link: https://github.com/midoks/zzz
