[package]
name = "test_web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
api = "0.2.0"
mime_guess = "2.0.5"
rust-embed = "8.7.2"
serde = { version = "1.0", features = ["derive"] }
