#:schema node_modules/wrangler/config-schema.json
name = "imageblog"
main = "src/index.js"
compatibility_date = "2023-05-18"

compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1