dev: false
title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- target
- logs
- templates
ext:
- rs
lang: rust
enablerun: true
action:
  before:
  - echo "before"
  after:
  - ./target/release/fastcdn start --daemon
  - ./target/release/fastcdn-api start
  - ./target/release/fastcdn-node start
  exit:
  - ./target/release/fastcdn stop
  # 生成工作空间文档
  # cargo doc --workspace --open
link: https://github.com/midoks/zzz
