[package]
name = "test_net"
version = "0.1.0"
edition = "2024"  # Rust 2024 Edition

[dependencies]
hyper = { version = "1.6", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4"
rand = "0.8"